In [3]:
import numpy as np
import cv2 as cv
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
x0=np.ones((25,1))

In [6]:
my_data = np.loadtxt(open("data1.csv", "rb"), delimiter=",", skiprows=0)

In [7]:
print(my_data)

[[0.99162116 0.44666542 0.65597108 0.99834467]
 [0.1933074  0.18007962 0.80394053 0.86105884]
 [0.17447959 0.85390996 0.93114117 1.16273488]
 [0.67937981 0.27640369 0.5308529  0.88457782]
 [0.87095971 0.48281909 0.8159076  1.03153045]
 [0.95523604 0.85417108 0.30272111 1.10059547]
 [0.57708151 0.55399871 0.40695119 0.97325893]
 [0.77514832 0.18284638 0.34366064 0.82101523]
 [0.70814549 0.53996647 0.7548035  1.037775  ]
 [0.03190035 0.97208511 0.36851772 1.09908536]
 [0.4764231  0.64148652 0.61553037 1.0362357 ]
 [0.16536392 0.36327653 0.86806665 0.94876873]
 [0.3642039  0.01010249 0.68629244 0.78794554]
 [0.74001565 0.72343428 0.2740373  1.02723658]
 [0.75933799 0.91298902 0.28318976 1.10686366]
 [0.36344185 0.93668547 0.34485102 1.1028901 ]
 [0.3607675  0.51017485 0.70355899 0.99470463]
 [0.13075238 0.63206436 0.55968954 1.00174999]
 [0.76707395 0.96155171 0.75677023 1.21461648]
 [0.46784969 0.02620726 0.91073375 0.83740954]
 [0.14019095 0.86600409 0.67784996 1.11859644]
 [0.57751715 

In [8]:
c=np.hsplit(my_data, 4)
Y=c[3];
X0=np.hstack([c[0],c[1],c[2]])
X=np.hstack([X0,x0])
print(X)

[[0.99162116 0.44666542 0.65597108 1.        ]
 [0.1933074  0.18007962 0.80394053 1.        ]
 [0.17447959 0.85390996 0.93114117 1.        ]
 [0.67937981 0.27640369 0.5308529  1.        ]
 [0.87095971 0.48281909 0.8159076  1.        ]
 [0.95523604 0.85417108 0.30272111 1.        ]
 [0.57708151 0.55399871 0.40695119 1.        ]
 [0.77514832 0.18284638 0.34366064 1.        ]
 [0.70814549 0.53996647 0.7548035  1.        ]
 [0.03190035 0.97208511 0.36851772 1.        ]
 [0.4764231  0.64148652 0.61553037 1.        ]
 [0.16536392 0.36327653 0.86806665 1.        ]
 [0.3642039  0.01010249 0.68629244 1.        ]
 [0.74001565 0.72343428 0.2740373  1.        ]
 [0.75933799 0.91298902 0.28318976 1.        ]
 [0.36344185 0.93668547 0.34485102 1.        ]
 [0.3607675  0.51017485 0.70355899 1.        ]
 [0.13075238 0.63206436 0.55968954 1.        ]
 [0.76707395 0.96155171 0.75677023 1.        ]
 [0.46784969 0.02620726 0.91073375 1.        ]
 [0.14019095 0.86600409 0.67784996 1.        ]
 [0.57751715 

In [9]:
X1=X.T
w=np.linalg.inv(X1.dot(X)).dot(X1).dot(Y);
print(w)

[[0.06513968]
 [0.40962719]
 [0.17938605]
 [0.63365882]]


In [39]:
image = cv.imread("三角形.jpg")
print(image.shape)
cv.imshow("三角", image)
cv.waitKey()

(523, 1024, 3)


-1

In [59]:
draw1=image.copy()
hsv1=cv.cvtColor(draw1, cv.COLOR_BGR2HSV)
low_hsv=np.array([125, 43, 46])
high_hsv=np.array([155, 255, 255])
mask = cv.inRange(hsv1, lowerb=low_hsv, upperb=high_hsv)
purple = cv.bitwise_and(draw1, draw1, mask=mask)
draw2=purple.copy()
ret1, th1 = cv.threshold(draw2, 230, 255, cv.THRESH_BINARY)
th2 = cv.cvtColor(th1, cv.COLOR_BGR2GRAY)
ret2, th3 = cv.threshold(th2, 1, 255, cv.THRESH_BINARY)

contours, hie = cv.findContours(th3, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
for i in contours:
    if len(i) < 10:
        continue
    x, y, w, h = cv.boundingRect(i)
    cv.rectangle(draw1, (x, y), (x+w, y+h), (0, 0, 255), 2)
cv.imshow("demo", draw1)
cv.waitKey()

-1